language: node_js

branches:
  only:
    - master

cache:
  directories:
  - "$HOME/.npm"

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: azure_web_apps
  username: flood-hack-user
  site: flood-hack
  skip_cleanup: true
  verbose: true
