language: node_js

branches:
  only:
    - master

cache:
  directories:
  - "$HOME/.npm"

install:
  - npm ci

script:
  - npm run build

before_deploy:
  - cd dist

deploy:
  provider: azure_web_apps
