language: node_js

branches:
  only:
    - master

cache:
  directories:
  - "$HOME/.npm"

install:
  - npm ci

script:
  - npm run build

before_deploy:
  - cd dist/flood-hack

deploy:
  provider: azure_web_apps
  skip_cleanup: true
